name: process_value
description: A declarative representation of a process
repository: https://github.com/timcreatedit/process_value
version: 0.1.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
dependencies:
  meta: ^1.9.1
